apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: NativeTransformer
  labels: 
    move2kube.konveyor.io/inbuilt: false
spec:
  class: "Executable"
# Added this  
  # isolated: true
  # override:
  #   matchLabels: 
  #     move2kube.konveyor.io/built-in: "true"
  directoryDetect:
    levels: -1
  consumes:
    Service:
      merge: false
  config:
    platforms: 
      - "linux"
    directoryDetectCMD: ["/usr/bin/python3", "./detect.py", "$M2K_DETECT_INPUT_PATH", "$M2K_DETECT_OUTPUT_PATH"]
    transformCMD: ["/usr/bin/python3", "./transform.py"]
